### ISSUE TITLE
app:processDebugResources Error retrieving parent for item (values-v24.xml)

### ISSUE THREAD

**Issue by joaoalbertocsjunior** [prscX/react-native-spruce#3]
I've managed to react-native link by re-creating the project.

Now, when i try to react-native run-android the application, build fails.

Here is the error:

```
:app:processDebugResources

C:\Users\mtlok\Desktop\pep\myspruce\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

C:\Users\mtlok\Desktop\pep\myspruce\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.


:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I have done something wrong? Why this is saying there is missing resource files?

**Comment by prscX** [comment]
Not sure @joaoalbertocsjunior, There are multiple solutions we can try:

- Android SDK 23 not install [9695](https://github.com/facebook/react-native/issues/9695)

- OR try this [10367](https://github.com/facebook/react-native/issues/10367)
```
cd android && gradlew clean
cd .. && react-native run-android
```

- If above solution does not work, we can remove the library then build again to verify is it because of library or some other issue

Thanks
Pranav

**Comment by joaoalbertocsjunior** [comment]
I will try and i will bring the results. Thank you again @prscX !

**Comment by joaoalbertocsjunior** [comment]
What i've learned so far:

I already have Android SDK 23.

gradlew clean does not work.

Im using a physical device with api 22. This might be the reason i'am facing this issue?

**Comment by prscX** [comment]
Not sure @joaoalbertocsjunior, is your app open source? if yes, I can download your project and try to build the same on my end.

Thanks
Pranav

**Comment by joaoalbertocsjunior** [comment]
This happens on a fresh created RN app. Already tried to re-create the project 3 times, but everytime when i yarn add react-native-spruce and react-native link,  i get the same error.

**Comment by prscX** [comment]
I will also check from my end, meantime can you please download API >= 23 device and verify the same.

Thanks
Pranav

**Comment by joaoalbertocsjunior** [comment]
Installing build tools >= 24 solved the issue. Material was introduced in API 24.

**Comment by prscX** [comment]
Thanks @joaoalbertocsjunior for verifying the same. I will specify the same in README.

Let me know in case you face any issues

Thanks
Pranav

**Comment by prscX** [comment]
Hi @joaoalbertocsjunior, Can I close the raised issue?

Thanks
Pranav

**Comment by prscX** [comment]
Hi @joaoalbertocsjunior, Closing this issue for now. Let me know in case you face any issues.

Thanks
Pranav
