### ISSUE TITLE
Could this framework work with react-native-web?

### ISSUE THREAD

**Issue by DavidGOrtega** [prscX/react-native-spruce#6]
Hi, I have seen that spruce is a wrapper for IOS and Android, however I have seen that there is a js folder in the project. Would the library be able to work with react native web or react web?

https://github.com/taobaofed/react-web   
https://github.com/necolas/react-native-web

**Comment by prscX** [comment]
Thanks @DavidGOrtega for the query.

I am sorry but it can not be supported on Web since it is a Native Module using native (Android & iOS) libraries which can not be ported for Web.

Thanks
Pranav
