### ISSUE TITLE
error in iOS example

### ISSUE THREAD

**Issue by gianpaj** [prscX/react-native-spruce#9]
```
TypeError: undefined is not a constructor (evaluating 'new _reactNativeSpruce.CorneredSort(60)')

This error is located at:
    in App (at renderApplication.js:33)

render
    App.js:8:36
```

The issue is here:
https://github.com/prscX/react-native-spruce/blob/7d4e556ab8e5cecc4f35ccd0c0998156a5ddd82b/SpruceExample/App.js#L8

steps
```
git clone git@github.com:prscX/react-native-spruce.git
cd react-native-spruce/SpruceExample
yarn
react-native run-ios
```

Got this warning when building the app:
```
The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
(1 command with analyzer issues)
```

Extra info:
```
$ react-native info

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

**Comment by prscX** [comment]
Thanks @gianpaj for raising the issue and providing a detailed description.

Which platform are you trying to test (Android/iOS)? 

> **Note:** On iOS it is not currently supported. Please refer below issue for the same:

[Issue: 101](https://github.com/willowtreeapps/spruce-ios/issues/101)

Soon I am planning to work on Objective-C wrapper in order enable this library for iOS as well.

Thanks
</ Pranav >

**Comment by gianpaj** [comment]
got it. would be useful probably to update the readme file then:
> React Native Spruce - iOS & Android
